#!/bin/sh

function untilsuccessful() {
	until "$@"; do
		echo Retrying: "$@"
		sleep 2
	done
}

# Couchbase Server start script.

IP=`hostname --ip-address`

set -e

if [ "$1" = 'couchbase-server' ]
then

    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root"
        exit 1
    fi

    # Create directories where couchbase stores its data
    cd /opt/couchbase
    mkdir -p var/lib/couchbase \
        var/lib/couchbase/config \
        var/lib/couchbase/data \
        var/lib/couchbase/stats \
        var/lib/couchbase/logs \
        var/lib/moxi
    chown -R couchbase:couchbase var

    # Start couchbase
    echo "Starting Couchbase Server -- Web UI available at http://<ip>:8091"
    gosu couchbase "$@" &
    PID=$!

    # Init Couchbase
    echo "Make Couchbase ($IP) the first cluster node"
    untilsuccessful couchbase-cli cluster-init -c $IP \
      --cluster-init-username=$CB_USERNAME \
      --cluster-init-password=$CB_PASSWORD \
      --cluster-init-ramsize=$CB_NODE_RAMSIZE
    untilsuccessful couchbase-cli bucket-create -c $IP \
      -u $CB_USERNAME -p $CB_PASSWORD \
      --bucket=default --bucket-ramsize=128
fi

# Leave the container with open shell
exec /bin/bash